// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: grpc/chat_service.proto

package chat_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChitChatInformationContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LamportTimestamp int64 `protobuf:"varint,1,opt,name=lamport_timestamp,json=lamportTimestamp,proto3" json:"lamport_timestamp,omitempty"`
	// Types that are assignable to These:
	//
	//	*ChitChatInformationContainer_Message
	//	*ChitChatInformationContainer_ConnectionRequest
	//	*ChitChatInformationContainer_DisconnectionRequest
	These isChitChatInformationContainer_These `protobuf_oneof:"these"`
}

func (x *ChitChatInformationContainer) Reset() {
	*x = ChitChatInformationContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_chat_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChitChatInformationContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChitChatInformationContainer) ProtoMessage() {}

func (x *ChitChatInformationContainer) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chat_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChitChatInformationContainer.ProtoReflect.Descriptor instead.
func (*ChitChatInformationContainer) Descriptor() ([]byte, []int) {
	return file_grpc_chat_service_proto_rawDescGZIP(), []int{0}
}

func (x *ChitChatInformationContainer) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (m *ChitChatInformationContainer) GetThese() isChitChatInformationContainer_These {
	if m != nil {
		return m.These
	}
	return nil
}

func (x *ChitChatInformationContainer) GetMessage() *ChitChatMessage {
	if x, ok := x.GetThese().(*ChitChatInformationContainer_Message); ok {
		return x.Message
	}
	return nil
}

func (x *ChitChatInformationContainer) GetConnectionRequest() *ConnectionRequest {
	if x, ok := x.GetThese().(*ChitChatInformationContainer_ConnectionRequest); ok {
		return x.ConnectionRequest
	}
	return nil
}

func (x *ChitChatInformationContainer) GetDisconnectionRequest() *DisconnectionRequest {
	if x, ok := x.GetThese().(*ChitChatInformationContainer_DisconnectionRequest); ok {
		return x.DisconnectionRequest
	}
	return nil
}

type isChitChatInformationContainer_These interface {
	isChitChatInformationContainer_These()
}

type ChitChatInformationContainer_Message struct {
	Message *ChitChatMessage `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
}

type ChitChatInformationContainer_ConnectionRequest struct {
	ConnectionRequest *ConnectionRequest `protobuf:"bytes,3,opt,name=connection_request,json=connectionRequest,proto3,oneof"`
}

type ChitChatInformationContainer_DisconnectionRequest struct {
	DisconnectionRequest *DisconnectionRequest `protobuf:"bytes,4,opt,name=disconnection_request,json=disconnectionRequest,proto3,oneof"`
}

func (*ChitChatInformationContainer_Message) isChitChatInformationContainer_These() {}

func (*ChitChatInformationContainer_ConnectionRequest) isChitChatInformationContainer_These() {}

func (*ChitChatInformationContainer_DisconnectionRequest) isChitChatInformationContainer_These() {}

type ConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_chat_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequest) ProtoMessage() {}

func (x *ConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chat_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_chat_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type DisconnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
}

func (x *DisconnectionRequest) Reset() {
	*x = DisconnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_chat_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisconnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectionRequest) ProtoMessage() {}

func (x *DisconnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chat_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectionRequest.ProtoReflect.Descriptor instead.
func (*DisconnectionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_chat_service_proto_rawDescGZIP(), []int{2}
}

func (x *DisconnectionRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type ChitChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ChitChatMessage) Reset() {
	*x = ChitChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_chat_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChitChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChitChatMessage) ProtoMessage() {}

func (x *ChitChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chat_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChitChatMessage.ProtoReflect.Descriptor instead.
func (*ChitChatMessage) Descriptor() ([]byte, []int) {
	return file_grpc_chat_service_proto_rawDescGZIP(), []int{3}
}

func (x *ChitChatMessage) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ChitChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_chat_service_proto protoreflect.FileDescriptor

var file_grpc_chat_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0xbc, 0x02, 0x0a, 0x1c, 0x43, 0x68, 0x69, 0x74,
	0x43, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x11, 0x6c, 0x61, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x10, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x39, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x69, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x50, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x11, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x59, 0x0a, 0x15, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x14, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x07, 0x0a,
	0x05, 0x74, 0x68, 0x65, 0x73, 0x65, 0x22, 0x30, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x14, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a,
	0x0f, 0x43, 0x68, 0x69, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x6e, 0x0a, 0x08, 0x43, 0x68, 0x69, 0x74, 0x43,
	0x68, 0x61, 0x74, 0x12, 0x62, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x2a, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x69, 0x74, 0x43,
	0x68, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x1a, 0x2a, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x69, 0x74, 0x43, 0x68, 0x61, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x28, 0x01, 0x30, 0x01, 0x42, 0x13, 0x5a, 0x11, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_chat_service_proto_rawDescOnce sync.Once
	file_grpc_chat_service_proto_rawDescData = file_grpc_chat_service_proto_rawDesc
)

func file_grpc_chat_service_proto_rawDescGZIP() []byte {
	file_grpc_chat_service_proto_rawDescOnce.Do(func() {
		file_grpc_chat_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_chat_service_proto_rawDescData)
	})
	return file_grpc_chat_service_proto_rawDescData
}

var file_grpc_chat_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_chat_service_proto_goTypes = []interface{}{
	(*ChitChatInformationContainer)(nil), // 0: chat_service.ChitChatInformationContainer
	(*ConnectionRequest)(nil),            // 1: chat_service.ConnectionRequest
	(*DisconnectionRequest)(nil),         // 2: chat_service.DisconnectionRequest
	(*ChitChatMessage)(nil),              // 3: chat_service.ChitChatMessage
}
var file_grpc_chat_service_proto_depIdxs = []int32{
	3, // 0: chat_service.ChitChatInformationContainer.message:type_name -> chat_service.ChitChatMessage
	1, // 1: chat_service.ChitChatInformationContainer.connection_request:type_name -> chat_service.ConnectionRequest
	2, // 2: chat_service.ChitChatInformationContainer.disconnection_request:type_name -> chat_service.DisconnectionRequest
	0, // 3: chat_service.ChitChat.Chat:input_type -> chat_service.ChitChatInformationContainer
	0, // 4: chat_service.ChitChat.Chat:output_type -> chat_service.ChitChatInformationContainer
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_chat_service_proto_init() }
func file_grpc_chat_service_proto_init() {
	if File_grpc_chat_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_chat_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChitChatInformationContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_chat_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_chat_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisconnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_chat_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChitChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grpc_chat_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ChitChatInformationContainer_Message)(nil),
		(*ChitChatInformationContainer_ConnectionRequest)(nil),
		(*ChitChatInformationContainer_DisconnectionRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_chat_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_chat_service_proto_goTypes,
		DependencyIndexes: file_grpc_chat_service_proto_depIdxs,
		MessageInfos:      file_grpc_chat_service_proto_msgTypes,
	}.Build()
	File_grpc_chat_service_proto = out.File
	file_grpc_chat_service_proto_rawDesc = nil
	file_grpc_chat_service_proto_goTypes = nil
	file_grpc_chat_service_proto_depIdxs = nil
}
